<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class BonesI extends Model
{
    //MASS ASSIGNABLE COLUMNS
    protected $fillable = [

        'entered_by',
        'entered_date',
        'notes',
        'has_file',
        'provenience',
        'designated_id',
        'front_cranial_left',
        'front_cranial_right',
        'parietal_left',
        'parietal_right',
        'occiptial_left',
        'occiptial_right',
        'temporal_left',
        'temporal_right',
        'tmj_left',
        'tmj_right',
        'mandible_left',
        'mandible_right',
        'zygomatic_left',
        'zygomatic_right',
        'maxilla_left',
        'maxilla_right',
        'nasal_left',
        'nasal_right',
        'lacrimal_left',
        'lacrimal_right',
        'inc_left',
        'inc_right',
        'palatine_left',
        'palatine_right',
        'sphenoid_left',
        'sphenoid_right',
        'ethmoid',
        'vomer',
        'hyoid',
        'thyroidcryoid',
        'ossicles',
        'unidentified_cranial',
        'incisors_number',
        'incisors',
        'canines_number',
        'canines',
        'premolars_number',
        'premolars',
        'molars_number',
        'molars',
        'unidentified_teeth',
        'cervical_1',
        'cervical_2',
        'cervical_36_num',
        'cervical_36',
        'cervical_7',
        'thoracic_19_num',
        'thoracic_19',
        'thoracic_10',
        'thoracic_11',
        'thoracic_12',
        'lumbar_14_num',
        'lumbar_14',
        'lumbar_5',
        'sacrum_num',
        'sacrum',
        'coccyx_num',
        'coccyx',
        'manubrium',
        'body',
        'xiphoid',
        'left_ribs_num',
        'left_ribs',
        'right_ribs_num',
        'right_ribs',
        'unidentified_axial',
        'scapula_left',
        'scapula_right',
        'glenoid_left',
        'glenoid_right',
        'clavicle_left',
        'clavicle_right',
        'med_epi_left',
        'med_epi_right',
        'ilium_left',
        'ilium_right',
        'auricular_left',
        'auricular_right',
        'pubis_left',
        'pubis_right',
        'symphysis_left',
        'symphysis_right',
        'ischium_left',
        'ischium_right',
        'acetabulum_left',
        'acetabulum_right',
        'patelia_left',
        'patelia_right',
        'unidentified_append',
        'file'

    ];


    //ASSIGNED TABLE
    protected $table = 'bone_tables';
}
