<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class BonesII extends Model
{
    //
    //MASS ASSIGNABLE COLUMNS
    protected $fillable = [

        'entered_by',
        'entered_date',
        'calcaneus',
        'capitate',
        'cuboid',
        'distPhalanges',
        'distPhalanges2',
        'femur_dist',
        'femur_epid',
        'femur_epip',
        'femur_mid',
        'femur_prox',
        'fibula_dist',
        'fibula_epid',
        'fibula_epip',
        'fibula_mid',
        'fibula_prox',
        'file',
        'hamate',
        'humerus_dist',
        'humerus_epid',
        'humerus_epip',
        'humerus_mid',
        'humerus_prox',
        'interCuneiform',
        'latCuneiform',
        'lunate',
        'medCuneiform',
        'metacarpals2',
        'metatarsals',
        'midPhalanges',
        'midPhalanges2',
        'navicular',
        'pisiform',
        'proxPhalanges',
        'proxPhalanges2',
        'radius_dist',
        'radius_epid',
        'radius_epip',
        'radius_mid',
        'radius_prox',
        'rfemur_dist',
        'rfemur_epid',
        'rfemur_epip',
        'rfemur_mid',
        'rfemur_prox',
        'rfibula_dist',
        'rfibula_epid',
        'rfibula_epip',
        'rfibula_mid',
        'rfibula_prox',
        'rhumerus_dist',
        'rhumerus_epid',
        'rhumerus_epip',
        'rhumerus_mid',
        'rhumerus_prox',
        'rradius_dist',
        'rradius_epid',
        'rradius_epip',
        'rradius_mid',
        'rradius_prox',
        'rtibia_dist',
        'rtibia_epid',
        'rtibia_epip',
        'rtibia_mid',
        'rtibia_prox',
        'rulna_dist',
        'rulna_epid',
        'rulna_epip',
        'rulna_mid',
        'rulna_prox',
        'scaphoid',
        'sesamoids',
        'sesamoids2',
        'talus',
        'tibia_dist',
        'tibia_epid',
        'tibia_epip',
        'tibia_mid',
        'tibia_prox',
        'trapezium',
        'trapezoid',
        'triquetral',
        'ulna_dist',
        'ulna_epid',
        'ulna_epip',
        'ulna_mid',
        'ulna_prox',
        'calcaneus_num',
        'capitate_num',
        'cuboid_num',
        'distPhalanges_num',
        'distPhalanges2_num',
        'hamate_num',
        'interCuneiform_num',
        'latCuneiform_num',
        'lunate_num',
        'medCuneiform_num',
        'metacarpals2_num',
        'metatarsals_num',
        'midPhalanges_num',
        'midPhalanges2_num',
        'navicular_num',
        'pisiform_num',
        'proxPhalanges_num',
        'proxPhalanges2_num',
        'scaphoid_num',
        'sesamoids_num',
        'sesamoids2_num',
        'talus_num',
        'trapezium_num',
        'trapezoid_num',
        'triquetral_num',
        'unidentified_extermities'

    ];


    //ASSIGNED TABLE
    protected $table = 'bone2_tables';
}
